# Generated by Django 3.1.2 on 2020-10-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201022_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirm_password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
